### ISSUE TITLE
BRPhoneNumberField not working

### ISSUE THREAD

**Issue by giancarloap** [django/django-localflavor#140]
I don't know if it's some conflict with my code. For me the input is always invalid even when i use the format xx-xxxx-xxxx on the form. I solved it cleaning the '-' minus myself, like this:

class CustomerAddressForm(forms.ModelForm):
    contact_phone = BRPhoneNumberField(help_text='XX-XXXX-XXXX ou XX-XXXXX-XXXX ou só os digitos')
(...)
def clean_contact_phone(self):
        self.cleaned_data['contact_phone'] = self.cleaned_data['contact_phone'].replace("-", "")
        return self.cleaned_data['contact_phone']

After writing this method, it worked. Is this normal, can you reproduce the situation?

**Comment by avelino** [comment]
Tested and worked normally, I'm using in many project!
I believe it is a mistake of implementation

**Comment by claudep** [comment]
The tests are here: https://github.com/django/django-localflavor/blob/master/tests/test_br.py#L69
If you can make the tests fail, we'll reopen the issue.
