### ISSUE TITLE
ImportError: cannot import name truncate_words on django 1.8

### ISSUE THREAD

**Issue by TaqiOfficial** [django/django-localflavor#147]
I am using django 1.8  and my code is as below.
```
from django.db import models
from localflavor.pk.models import PKStateField

class Location(models.Model):
    city = models.CharField(max_length=64)
    state = PKStateField(default="PK-IS", blank=True)
```
and I am getting this error - 
`ImportError: cannot import name truncate_words`

**Comment by benkonrath** [comment]
`truncate_words` doesn't seem to be used in the version of django-localflavor from master. Which version are you having this problem with?

**Comment by TaqiOfficial** [comment]
I guess the latest version it is.

**Comment by benkonrath** [comment]
`truncate_words` is also not used in version 1.0 or 1.1. I'm pretty sure that this isn't a bug in django-localflavor as the tests are currently passing on Django 1.8 and `localflavor.pk.models` seems to be tested well. 

https://travis-ci.org/django/django-localflavor

Can you post a full stack trace along with the version of django-localflavor? It's hard to help you out any further without this information. Thanks.

**Comment by claudep** [comment]
I doubt the bug is in localflavor.
