### ISSUE TITLE
Wrong french translation for XXXX zip code

### ISSUE THREAD

**Issue by camillobruni** [django/django-localflavor#159]
The following translation in `fr` is wrong:
```
#: at/forms.py:25 ch/forms.py:29 no/forms.py:24
msgid "Enter a zip code in the format XXXX."
msgstr "Saisissez un code postal norvégien au format XXXX."
```

It is specific to the novergian zip code whilst the same translation string is used for austrian and swiss zip codes. Stripping "norvégien" should do the trick.

**Comment by claudep** [comment]
Thanks, but that was already reported and fixed in Transifex. This will be integrated in the next release of django-localflavor.

**Comment by camillobruni** [comment]
that's a pity since this problem exists for quite a while. any chance to push at least the latest translation to the master?

**Comment by claudep** [comment]
I've just pushed the updated en po file to master, so the strings from your patch should be available to translate on Transifex. Let's make sure we have at least French and German translations for them, then I'll get back the translations and ask the maintainers for a new release (hopefully within 2 weeks).

**Comment by camillobruni** [comment]
thanks :)
