### ISSUE TITLE
Models Need Deconstruct Methods?

### ISSUE THREAD

**Issue by mlissner** [django/django-localflavor#161]
I'm just upgrading to Django 1.7 and I'm learning about the [deconstruct methods that are required on custom fields][decon]. 

I use the US localflavor and I'm quite surprised that `deconstruct` methods haven't been added? Looking further, it seems there's no `deconstruct` method for *any* flavor. 

Is there a deliberate reason for this? If not, I'll write a quick PR to add these to US, but I don't have time to do it for all the locales. 

Thanks.

[decon]: https://docs.djangoproject.com/en/1.8/howto/custom-model-fields/#custom-field-deconstruct-method

**Comment by jezdez** [comment]
Yeah, this just hasn't come up I think, see my comment in #162.

**Comment by graup** [comment]
Just ran into this bug trying to use `localflavor.generic.validators.EANValidator`. It breaks on running `makemigrate`. (Django 1.9, localflavor 1.2)

**Comment by benkonrath** [comment]
@graup Thanks for the report. I'm planning to look into this during the Django EU sprints this weekend.

**Comment by benkonrath** [comment]
@graup Your specific issue with the validator should now be fixed - thanks @unloder!
