### ISSUE TITLE
localflavor-it: wrong error string in ITSocialSecurityNumberField

### ISSUE THREAD

**Issue by zarelit** [django/django-localflavor#164]
The original error string in it/forms.py is "Enter a valid Social Security number." that is literally translated in the Italian language file.

While this is good for the same string in another context (e.g. the Mexican forms.py) it has the wrong meaning if used in Italian applications; the error string should be something like "Enter a valid Fiscal Code" or "Inserisci un Codice Fiscale valido".

The string "Inserisci un numero di Assistenza Sociale valido" cannot be understood by Italian non English-speaking people.

**Comment by claudep** [comment]
@yakky, @pauloxnet, would you support using "Enter a valid Fiscal Code" in this error message?

**Comment by zarelit** [comment]
I've actually found that "Agenzia Delle Entrate" (Italian revenue agency) actually calls it "Tax Code" in their English documents. 
http://www1.agenziaentrate.gov.it/english/italian_taxation/tax_code.htm

I would use "Enter a valid Tax code" in the source and "Inserisci un Codice Fiscale valido" as the Italian translation

**Comment by yakky** [comment]
@zarelit @claudep Above PR should fix the error message. The italian translation must be fixed on transifex after merging

**Comment by zarelit** [comment]
@yakky As you wish, they're almost the same, except that yours changes the string in the .po file and makes the comment more clear. I would go for yours.

**Comment by yakky** [comment]
@zarelit we've been both quite quick ! Thanks @claudep
