### ISSUE TITLE
Testing without tox

### ISSUE THREAD

**Issue by oorestisime** [django/django-localflavor#181]
Hello,

I am packaging localflavor for Debian and I am running into some problems with the test suite. If I don't use tox most of the tests fail ( https://reproducible.debian.net/rb-pkg/testing/amd64/django-localflavor.html the rbuild.) I tried setting the DJANGO_SETTINGS_MODULE but then other tests fail.

I can't use tox since tox creates virtualenv through pip. 

So i am wondering if there are any tips on how to run tests without tox. 

P.S I am preparing a new upload to fix this and i saw that you might make a new release. Is this happening in the following days (2 weeks)? This would avoid making two uploads ;)

**Comment by benkonrath** [comment]
Running `invoke test` outside of tox on 1.1 seems to be broken. On master it's working (without having to set `DJANGO_SETTINGS_MODULE`). I'm not sure the specific cause so waiting for the 1.2 release would be the best solution. I'm not sure when that's going to happen though.

**Comment by benkonrath** [comment]
Just a quick follow up ... I'll try to make time for the 1.2 release within the next 2 weeks. This is a nice push to get it it out. I'll want to check-in with the other maintainers first to see if they agree.

**Comment by oorestisime** [comment]
Ok thanks a lot. I ll be waiting the release then before uploading anything.

**Comment by benkonrath** [comment]
See #183.

**Comment by benkonrath** [comment]
I just release 1.2. Can you test to see if your problem is now fixed? Thanks.

**Comment by oorestisime** [comment]
hey thanks for releasing this so quickly.. running invoke test gives me
```log
Python version: 2.7.10+ (default, Oct 10 2015, 09:11:24) 
[GCC 5.2.1 20151028]
No file to run: 'test'
```
invoke docs works find though

Am i missing something?
Thanks for your help

**Comment by benkonrath** [comment]
It's working for me with invoke 0.11.1 (as used in the tests - see `tests/requirements.txt`) and Python 2.7.5 on EL 7. Which version of invoke are you using? Maybe that's causing the problem.

**Comment by oorestisime** [comment]
hm i made a virtualenv and pip installed the requirements.. here is a freeze
```log
coverage==3.7.1
django-discover-runner==1.0
flake8==2.2.5
invoke==0.11.1
mccabe==0.3.1
pep8==1.6.2
pyflakes==1.0.0
six==1.8.0
```
running tox works fine!

**Comment by benkonrath** [comment]
Here's my virtualenv:

```
% pip freeze
coverage==3.7.1
Django==1.8.7
django-discover-runner==1.0
flake8==2.2.5
invoke==0.11.1
mccabe==0.3.1
pep8==1.6.2
pyflakes==1.0.0
six==1.8.0
```
Which version of Django are your testing against?

**Comment by oorestisime** [comment]
ok thanks.. I was checking against Django 1.7.10. Just checked with 1.8.7 and worked. Although shouldn't it work with 1.7 as well?

**Comment by benkonrath** [comment]
Yeah, we test against Django 1.7 in the tox build so it should work. You need it work with 1.7, right?

**Comment by benkonrath** [comment]
I just tested with Django 1.7.10 in my virtualenv instead of Django 1.8.7 and `invoke test` is working.

**Comment by oorestisime** [comment]
Oh that's true.. the only difference is that i was using django from Debian and not from pip. I ll have to investigate this a bit more but at least now i know that it works locally. 
Thanks again for all your help

**Comment by benkonrath** [comment]
No problem.

There might be something wrong with the setup of your virtualenv. As far as I know, it is possible to mix in system installed packages but you have to pass some options to virtualenv for this.

I'll keep this issue open for now but let me know if you have anymore questions or when we can close this. Thanks.

**Comment by oorestisime** [comment]
OK i managed to solve the problems. I ll finish and upload the new release to Debian. 
Once again thanks for the help
