### ISSUE TITLE
1.2 release on 27 November 2015

### ISSUE THREAD

**Issue by benkonrath** [django/django-localflavor#183]
I'm planning to make a 1.2 release on 27 November 2015.

@maintainers I'm planning to make the release without a major push for additional PRs to merged. That said, if there is a feature you'd like to see in 1.2 and it's not merged yet, you have a few days to work on it.

@claudep Will I need to do change something on Read the Docs to get the docs for the 1.2 tag setup correctly. Or is it automatic?

**Comment by claudep** [comment]
AFAIK and providing the commit hooks are properly set up, it's all automatic. See also http://read-the-docs.readthedocs.org/en/latest/versions.html

**Comment by jezdez** [comment]
@benkonrath #184 seems like a good thing to fix first

**Comment by benkonrath** [comment]
Yep, just didn't have time to check it out yet.

**Comment by benkonrath** [comment]
I'm putting together the changelog for the release so hopefully I'll have things ready in a hour or two.

@claudep Do you have time to update the translations? I'm not sure if any of the translations have been updated since your last update but it would be nice to double check this. Thanks.

**Comment by claudep** [comment]
I can do it now.

**Comment by benkonrath** [comment]
Thanks.

**Comment by claudep** [comment]
Done.

**Comment by benkonrath** [comment]
Version 1.2 has been released. Thanks for your help @claudep. And thanks to everybody who contributed to this release.

**Comment by claudep** [comment]
\o/
