### ISSUE TITLE
US Docs data is weird

### ISSUE THREAD

**Issue by orf** [django/django-localflavor#184]
The data includes the `repr` of a Django localproxy: http://django-localflavor.readthedocs.org/en/latest/localflavor/us/#data

Perhaps this should be changed?

**Comment by jezdez** [comment]
https://github.com/django/django-localflavor/blob/master/docs/extensions/promises.py was supposed to fix that actually, something must have broken it

**Comment by jezdez** [comment]
Probably related to 0d48410f7b4a4f885d442cd109888c69bc3d612e? @benkonrath do you know anything about this?

**Comment by benkonrath** [comment]
I was trying to fix failure in the docs test build (see #149). I suppose a quick fix is to revert that change and use Sphinx 1.2 . I should have time to investigate tomorrow,

**Comment by benkonrath** [comment]
It looks like I didn't also set `lazy_safe_repr` when I updated to Sphinx 1.3. The updated docs should be posted shortly. @orf Thanks for reporting this issue.
