### ISSUE TITLE
AUPhoneNumberField improvements

### ISSUE THREAD

**Issue by KyeRussell** [django/django-localflavor#185]
Hey,

It has occurred to me that AUPhoneNumberField isn't as good as it could be. At the moment it strips parentheses/WS/hyphens which is great, but it doesn't do much beyond that. In fact, the existing validation check (exactly 10 digits) is **incorrect** as it rejects valid Australian phone numbers.

Australia's phone numbering system is very well documented on Wikipedia, as well as the ACMA website. I'm happy to put the work into stricter (or at least correct) validation, but - before I put effort into writing the necessary code - I was wondering if anyone knew of any rationale for the current setup that I'm missing.

Cheers.

**Comment by benkonrath** [comment]
I don't know the specific history of the AU module but if it's wrong, we'll definitely accept a PR to fix it. It's helpful to include links to sources such as Wikipedia and ACMA that show what the correct validation should be. Thanks.

**Comment by benkonrath** [comment]
I just wanted to point out PR #142. It fixed the AU phonenumber fields using the libphonenumber library which seems like a good way forward for django-localflavor. I'll try to make some time to look at that PR in the next week or two.

**Comment by KyeRussell** [comment]
That looks really good! Haven't heard of that library before but since it's Google I'll assume they've done it correctly :ok_hand:
