### ISSUE TITLE
Question on Django local flavor

### ISSUE THREAD

**Issue by btaek** [django/django-localflavor#193]
I am a newbie Django developer in Korea, and I learned about Django local flavor today. But, unfortunately, I find out Django local flavor does not include Korea (South Korea). My questions are:
- Do you have a plan to add Korea to one of following versions of local flavor in near future?
- If there is no plan to add Korea to local flavor anytime soon, can I suggest the Django local flavor team to consider adding Korea to local flavor?

**Comment by claudep** [comment]
Hi btaek,

There are no development "plans", only patches/code written by contributors like you. So if anyone is proposing code adding support for a Korea localflavor, it will get reviewed and finally included in a future release. We're looking forward to your contribution :-)

**Comment by benkonrath** [comment]
@btaek I just want to add that contributing to this project would be a good way to get more experience with Django. Your code contribution would be reviewed by experienced Django developers and you'll get feedback on how you can improve the pull request that you submit.

The easiest thing to do is to create a pull request with one form or model field for South Korea. Feel free to ask if you have any questions.

**Comment by btaek** [comment]
Thanks for feedback. I will look into making a code contribution to local flavor. Will post a question if I have one.
