### ISSUE TITLE
Brazilian CPF and CNPJ are not in .br.models as changelog 1.2 (2015-11-27) says

### ISSUE THREAD

**Issue by diegotolentino** [django/django-localflavor#196]
The fields BRCPFField and BRCNPJField not present in tag v1.2 as change log say. 

see:
http://django-localflavor.readthedocs.org/en/latest/changelog/#id2
https://github.com/django/django-localflavor/blob/1.2/localflavor/br/models.py

**Comment by benkonrath** [comment]
The fields are implemented as form fields, not model fields:
https://github.com/django/django-localflavor/blob/master/localflavor/br/forms.py
