### ISSUE TITLE
IBANField with Nordea extensions does not validate

### ISSUE THREAD

**Issue by synotna** [django/django-localflavor#202]
Using an IBANField with Nordea extensions enabled does not validate when trying to use a Nordea IBAN e.g. from Ukraine, UA573543470006762462054925026

Tested wtih:

Django 1.9.4
django-localflavor 1.2

**models.py**
```python
from django.db import models

from localflavor.generic.models import IBANField


class Partner(models.Model):
    iban = IBANField(use_nordea_extensions=True)
```

**admin.py**
```python
from django.contrib import admin

from .models import Partner


@admin.register(Partner)
class PartnerAdmin(admin.ModelAdmin):
    pass
```

![ibanfield](https://cloud.githubusercontent.com/assets/3313126/13570835/0dbdc4ec-e471-11e5-916f-a7a6771e493d.jpg)

**Comment by synotna** [comment]
I tried to debug myself but got lost in django internals; as far as I can tell, the extended validator is somehow forgotten when the ModelForm is instantiated around get_form/modelform_factory

**Comment by benkonrath** [comment]
Thanks for the bug report. I'll try to look into this in the next day or two.

**Comment by benkonrath** [comment]
@synotna My time is a bit limited today but I can spend a few minutes on this. 

One quick fix for supporting the Ukraine IBAN is to use the latest version of localflavor from master. The Ukraine IBAN is now officially part of the IBAN standard and I recently updated the official IBAN dictionary which means you don't have to use Nordea extensions option to validate Ukraine IBANs. Of course this is still a bug and I'd like to fix it but at least there's a way around the problem for you.

**Comment by benkonrath** [comment]
I have a failing test case for this. I'll pick this up during the DjangoCon EU sprints 2 / 3 April. Thanks again for reporting this problem.

**Comment by synotna** [comment]
Awesome, thank you & good luck at the con, looking forward to the talks coming out of it!
