### ISSUE TITLE
Fix style warnings and enable build failures for violating the style

### ISSUE THREAD

**Issue by Dunedan** [django/django-localflavor#214]
#212 enabled style checking via `prospector`. This style checking is currently also done automatically via TravisCI for every new commit, but because of the number of current style violations failing the build because of style violations is disabled via passing the `--zero-exit` parameter to `prospector`.

After all style warnings got fixed enabling build failures for new style violations would be an option.

**Comment by unloder** [comment]
Styling errors that were not fixed, and marked with # noqa: 

localflavor/id_/forms.py
  Line: 111
    mccabe: MC0001 / IDLicensePlateField.clean is too complex (12)

localflavor/no/forms.py
  Line: 46
    mccabe: MC0001 / NOSocialSecurityNumber.clean is too complex (13)

localflavor/sg/forms.py
  Line: 62
    pep8: N801 / class names should use CapWords convention (col 7)

https://github.com/django/django-localflavor/issues/258

localflavor/us/us_states.py
  Line: 153
    pep8: E501 / line too long (137 > 120 characters) (col 121)
