### ISSUE TITLE
Releasing 1.3 on 6 May 2016

### ISSUE THREAD

**Issue by benkonrath** [django/django-localflavor#228]
I was hoping to get to the release before my vacation but I'm short of time right now. I will do the 1.3 release on 6 May 2016.

@claudep Are you able to update the translations before then? I can send add a comment on the 5th to remind you if required. Thanks.

**Comment by claudep** [comment]
Sure, will do.

**Comment by claudep** [comment]
Translations updated.

**Comment by benkonrath** [comment]
Thanks @claudep! 1.3 has been released.

**Comment by claudep** [comment]
Thanks Ben!
