### ISSUE TITLE
Depricate non pep8 compliant class and method names

### ISSUE THREAD

**Issue by unloder** [django/django-localflavor#258]
**class SGNRIC_FINField(CharField):**
The name of this field could not be changed for backwards compatibility reasons. This field should get renamed and eventually deprecated when a deprecation solution will get implemented.
localflavor/sg/forms.py
  Line: 62
    pep8: N801 / class names should use CapWords convention (col 7)

**def DV_maker(v):**
/home/unloder/WWW/django-localflavor/localflavor/br/forms.py
    line 100

**mccabe: MC0001 / IDLicensePlateField.clean is too complex (12)**
localflavor/id_/forms.py
Line: 111

**mccabe: MC0001 / NOSocialSecurityNumber.clean is too complex (13)**
localflavor/no/forms.py
Line: 46

**pep8: E501 / line too long (137 > 120 characters) (col 121)**
localflavor/us/us_states.py
Line: 153

**Comment by benkonrath** [comment]
These issues are all fixed.
