### ISSUE TITLE
refactor complex methods

### ISSUE THREAD

**Issue by unloder** [django/django-localflavor#261]
These methods are too complex to pass prospector so should be refactored

**mccabe: MC0001 / IDLicensePlateField.clean is too complex (12)**
localflavor/id_/forms.py
Line: 111

**mccabe: MC0001 / NOSocialSecurityNumber.clean is too complex (13)**
localflavor/no/forms.py
Line: 46

**Comment by vladimirnani** [comment]
@unloder what command do you run to see these exceptions

**Comment by benkonrath** [comment]
@vladimirnani Remove the 'noqa' comment in the referenced lines and run the prospector command.

**Comment by vladimirnani** [comment]
@benkonrath ok thanks
