### ISSUE TITLE
ABN validation

### ISSUE THREAD

**Issue by bpinnell** [django/django-localflavor#266]
When using Django Admin with a model containing an AuBusinessNumber field, the field is displayed with spaces. Upon saving the model, validation fails because those spaces, so even if you don't touch that field you have to delete the spaces in order to save the model.

**Comment by benkonrath** [comment]
Thanks for reporting the issue. It should be fixed in master. You need to install that specific version until I have a chance to release 1.4 (hopefully sometime in the next couple of weeks).
