### ISSUE TITLE
MD localflavor

### ISSUE THREAD

**Issue by vladimirnani** [django/django-localflavor#269]
Add Moldova flavor. 

Fields to consider:
**IDNO** (Fiscal number)
Example: `1010600026974`
Examples (Old): `169011,25038012`

Not sure how to deal with legacy IDNO, new ones are always following this pattern `\d{13}`.

**Comment by benkonrath** [comment]
If the old IDNO numbers are still valid in Moldova, you should have 2 validations in the MDIDNOField. Just detect which version the user entered and run the correct validation. Does this help?

**Comment by vladimirnani** [comment]
Yes. Thanks. Ill have two different validators.

**Comment by benkonrath** [comment]
You could also have the validation logic for both versions of the IDNO in the same validator. It really depends on whether or not a new and old validator would be useful independently of each other. As a developer of website targeting Moldova, I probably just want to know if the IDNO is valid and I don't really care if it's the old or new version. But that's only something a Moldovan developer would know so I have to trust your knowledge how things work with the IDNO locally.

**Comment by vladimirnani** [comment]
I guess I'll have two fields. One for current idno format and one for
fallback.


On Nov 26, 2016 8:07 PM, "Ben Konrath" <notifications@github.com> wrote:

You could also have the validation logic for both versions of the IDNO in
the same validator. It really depends on whether or not a new and old
validator would be useful independently of each other. As a developer of
website targeting Moldova, I probably just want to know if the IDNO is
valid and I don't really care if it's the old or new version. But that's
only something a Moldovan developer would know so I have to trust your
knowledge how things work with the IDNO locally.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/django/django-localflavor/issues/269#issuecomment-263077423>,
or mute the thread
