### ISSUE TITLE
upgrade to Prospector 0.12.5

### ISSUE THREAD

**Issue by benkonrath** [django/django-localflavor#290]
I've fixed the version or Prospector to 0.12.4 because version 0.12.5 adds some additional checks that fail on localflavor. These failures need to be addressed - either disable the check or fix the problem - before we can upgrade to Prospector 0.12.5.

**Comment by claudep** [comment]
Also let's check that we don't pass more time fixing "cosmetic" issues than working on real functionalities!

**Comment by benkonrath** [comment]
Yeah, of course. That's why I just disabled the upgrade to 0.12.5. I wanted to make an issue for this just to highlight that I made this change. I have no intention to work on this anytime soon so it's also ok by me if we close this issue.

**Comment by benkonrath** [comment]
Fixed by #412
