### ISSUE TITLE
release version 1.5 on 26 May 2017

### ISSUE THREAD

**Issue by benkonrath** [django/django-localflavor#291]
I will release version 1.5 on Friday 26 May 2017.

@claudep I just updated the translation catalog which is why I'm waiting a week to do the 1.5 release. Can you update the translations on Thursday 25 May or Friday 26 May? Thanks.

**Comment by claudep** [comment]
Sure, just re-ping me at that time if needed.

**Comment by claudep** [comment]
Done in 1cb0111

**Comment by benkonrath** [comment]
Thanks @claudep. I've just released localflavor 1.5.

**Comment by claudep** [comment]
Thanks Ben!
