### ISSUE TITLE
Override choices in State field

### ISSUE THREAD

**Issue by ka7eh** [django/django-localflavor#293]
I noticed `choices` attribute on `us.models.USStateField` cannot be overriden and always uses `US_STATES`. I'd like to override that with `us.us_states.STATE_CHOICES` instead.

I know I can do it on a form level and validate against `STATE_CHOICES`, but I'm fetching my choices using Django Rest Framework which looks at whatever choices is set on the model level.

Should the above-mentioned field be updated to accept a subset of `US_STATES` as choices?

**Comment by ka7eh** [comment]
Never mind this, I overrode the state field in my serializer.

**Comment by benkonrath** [comment]
If you want to fix this generally, you can make a PR to allow `choices` to be overridden. Just make sure that  the default `STATE_CHOICES` is kept. Thanks.

**Comment by ka7eh** [comment]
Sure, I can do that. I just wanted to know the rationale behind it and whether that behavior was intentional or not.

**Comment by benkonrath** [comment]
I'm not sure the original rationale - the code in localflavor has been developed by many people over the course of many years. In general if there's a concrete use-case for a change and somebody is willing to make a PR, we'll accept it.
