### ISSUE TITLE
release version 1.6 on 21 November 2017 

### ISSUE THREAD

**Issue by benkonrath** [django/django-localflavor#312]
I will release version django-localflavor 1.6 on 21 November 2017 so that I can prepare for the 2.0 release of localflavor to match Django 2.0.

**Comment by benkonrath** [comment]
@claudep Can you update the translations on 20 or 21 November?

**Comment by claudep** [comment]
Sure, please ping me if I forget.

**Comment by benkonrath** [comment]
@claudep Just a reminder to update the translations for today's release. Thanks.

**Comment by claudep** [comment]
Sorry, working on it now.

**Comment by claudep** [comment]
Ben, do you think it'd be a good idea to remove source lines from po files (doing an msgcat --no-location on each po file before commit)?

**Comment by benkonrath** [comment]
I think it would be fine. But since I don't do any translations, I don't know what the impact this has on the translations or for translators. Is the benefit just that the translation updates don't change when the source text moves around in the file based on other changes?

**Comment by claudep** [comment]
Yes, the benefit is shorter commits. The en.po should keep the source locations so Transifex is still able to give that context information to translators.

**Comment by benkonrath** [comment]
Ok, sounds good. Is it possible to add this to the `pull_translations` task? I don't know if you use this task but it would be nice to have translation update procedure documented somewhere.

**Comment by claudep** [comment]
Oh, I didn't know about `tasks.py`! Will try to update it.

**Comment by claudep** [comment]
See https://github.com/django/django-localflavor/pull/313

**Comment by benkonrath** [comment]
I just want to confirm the #313 also had the updated translations. It's a big diff so it's hard to read. I'll make the release once I know that the translations have been updated.

**Comment by claudep** [comment]
No, it didn't include them, I just pushed them in ca6fcf8
Sorry for being late.

**Comment by benkonrath** [comment]
1. 6 has been released.

**Comment by claudep** [comment]
\o/
