### ISSUE TITLE
django-localflavor 2.0 - release compatible with Django 2.0

### ISSUE THREAD

**Issue by benkonrath** [django/django-localflavor#322]
I'm filing this issue as a place to discuss the upcoming 2.0 release of django-localflavor.

I'd like to get this release out as soon as possible. The only thing blocking this release is django-phonenumber-field's missing support for Django 2.0. Since we're removing the phone number fields in localflavor, there should be an option for users to migrate to. I made a PR to fix this already but I'd like to have it merged into the django-phonenumber-field repo before cutting the release. 
https://github.com/stefanfoulis/django-phonenumber-field/pull/196

If you need to use django-localflavor with Django 2.0, you can use the master branch until this is released. If you need to use phone number fields with Django 2.0, you'll have to use the code in my PR to django-phonenumber-field until it's merged / released.

**Comment by scott-weaver** [comment]
Do you know when 2.0 will be officially released?

**Comment by benkonrath** [comment]
I'm hoping to release 2.0 before the end of the year. Our official target is within one month of the compatible Django release. Having my Django 2.0 PR at least merged in django-phonenumber-field is the only real blocker but I'm not planning to extend the one month target just for this.

**Comment by benkonrath** [comment]
@claudep Could you update the translations to prepare for the 2.0 release if you have a chance in the next couple of days? Thanks!

**Comment by claudep** [comment]
Done.

**Comment by benkonrath** [comment]
Thanks Claude. I've just released django-localflavor 2.0.
