### ISSUE TITLE
A fr localflavor package

### ISSUE THREAD

**Issue by frague59** [django/django-localflavor#326]
Hi,
I'm using django / django-localflavor for many years, on `legacy` projects, (I've started working with django 1.2 / 1.3 I think)

Those projects has been upgraded with regularity, adding functionalities, but I'm embarrassed with the 2.0 release of django-localflavor: I don't find my FRPhoneNumberField(s) anymore. Here in France, we have a really particular way to spell our phone numbers: 0X XX XX XX XX, with X as digits, which is very cultural. Digit pairs are spelled as 100 based number, aka. "23" is spelled "thenty-three" (vingt-trois en français) or zero-six for 06.

The django-phonenumber-field package provides an international way to validate the phone number, which is a good thing... but never used here in France : most french peoples don't know about those phone number formats...

I could:
+ build a new class "from scratch" (copying code from https://github.com/Gu1/django-localflavor-fr) and copy / paste code for the many projects I manage (~10 running projects)
+ build my own package from sources found in https://github.com/Gu1/django-localflavor-fr, but I think it will overlap the django-localflavor. This repository has not been upgraded for 5 years !
+ or build a new django-localflavor-fr package, but I don't know what to put in it.
 
My question is: 
+ What is the best option ? I would prefer to pip install the package from pypi...

Sorry for my poor english... and thanks for your help !

**Comment by claudep** [comment]
Hi François,
You are aware that those phone number fields have been removed in favor of `django-phonenumber-field`, right?
So are you saying that the equivalent in `django-phonenumber-field` is not as flexible as the old `FRPhoneNumberField`? Don't you think that `django-phonenumber-field` could be extended to support the French syntax?

**Comment by frague59** [comment]
Sorry, I've tested it completely, and `django-phonenumber-field` actually works... I've been too quick to post an issue on it.
