### ISSUE TITLE
Why not model fields?

### ISSUE THREAD

**Issue by marcinn** [django/django-localflavor#333]
I wonder why this package contains form fields instead of model fields.

**Comment by andrelramos** [comment]
+1

**Comment by benkonrath** [comment]
There actually are some model fields in localflavor. I think this "forms first" setup of localflavor comes from decisions made when this code was part of Django. I wasn't involved with then project at that stage so I'm only guessing. Pull requests are welcome that add model fields.

I'm closing this issue as I think I answered the question. If you feel this topic still needs some discussion, feel free to re-open it.
