### ISSUE TITLE
Propposal: Include `code` in ValidationError

### ISSUE THREAD

**Issue by fpuga** [django/django-localflavor#338]
Most of the django core validators like [EmailValidator](https://github.com/django/django/blob/master/django/core/validators.py#L191), set the `code` parameter to `invalid`. I think that this can also be done in localflavor.

For example this can be used in testing to check a validation without need to parse the localized message.

**Comment by claudep** [comment]
Makes sense.

**Comment by benkonrath** [comment]
@fpuga Thanks for the proposal. Would you be interested in contributing this change to localflavor?
