### ISSUE TITLE
IBANFormField error with Django 1.10.7

### ISSUE THREAD

**Issue by elpaso** [django/django-localflavor#340]
```
Exception Type: | AttributeError
-- | --
'IBANFormField' object has no attribute 'empty_value'
/home/.virtualenvs/mayan2/local/lib/python2.7/site-packages/localflavor/generic/forms.py in to_python, line 93
```

I checked 1.6.2 too but the code looks the same.

**Comment by benkonrath** [comment]
django-localflavor 2.0 dropped support Django 1.10 because it's no longer supported.

Does the problem happen with version 1.6.2 as well?

**Comment by elpaso** [comment]
yes, I ended up with https://github.com/elpaso/django-localflavor/commit/d24c3aeb27ba135f75d6871f668b9a22d7cdd032

**Comment by benkonrath** [comment]
@elpaso Since you haven't replied, I'm assuming you're ok with the fix you have. Feel free to re-open and reference this issue in any pull request you make to the 1.6.x branch if you want to help fix the problem. Thanks.
