### ISSUE TITLE
Proposal: Form and model field for country?

### ISSUE THREAD

**Issue by yourcelf** [django/django-localflavor#348]
Would a form field and model field for specifying a Country be within the scope of `django-localflavor`?

The [`localflavor.generic.countries.iso_3166`](https://github.com/django/django-localflavor/blob/master/localflavor/generic/countries/iso_3166.py) module already contains a list of ISO 3166-1 alpha-2 country codes.  This could be trivially updated to include the name of the country as a two-tuple (similar to [us_states](https://github.com/django/django-localflavor/blob/master/localflavor/us/us_states.py#L20)), and then a trivial form field and model field with the country names as choices and alpha-2 codes as values.

If this sounds like a good idea, I'll send a PR.

**Comment by ambsw-technology** [comment]
I was also surprised the functionality didn't exist.  I agree that duplication is bad and wonder if there'd be a logical way to incorporate the 3rd party library as a "best practice" e.g. in a documentation section for "country codes".

**Comment by carltongibson** [comment]
Closing as per Ben's comments above.
