### ISSUE TITLE
US SSN (USSocialSecurityNumberField) accepts numbers beginning with "900" through "999"

### ISSUE THREAD

**Issue by tadeck** [django/django-localflavor#35]
As per:
- [Wikipedia entry](http://en.wikipedia.org/wiki/Social_Security_number#Valid_SSNs) (treat it as starting point),
- [Social Security Administration FAQ page](http://ssa-custhelp.ssa.gov/app/answers/detail/a_id/425),

Social Security Numbers beginning with "9" are not valid.

Failing tests are ready, fix is on the way.

**Comment by nrogers64** [comment]
The comment needs to be updated:

https://github.com/django/django-localflavor/blob/1.1/localflavor/us/forms.py#L75-L76

**Comment by tadeck** [comment]
@nrogers64: You are right. Docstring is no longer correct.
