### ISSUE TITLE
Feature Request: Improve PhoneNumberField searching in admin

### ISSUE THREAD

**Issue by darkpixel** [django/django-localflavor#356]
I use the US PhoneNumberField in an application and I regularly use the admin interface to search for numbers.  I frequently forget and search using the format '3609991234' and get zero results.  If I search using the format '360-999-1234' search returns the record.  I haven't looked at the underlying code yet, but I would love to see the ability to search for numbers without having to remember to include the dashes.

**Comment by benkonrath** [comment]
The phone number fields have been removed in 2.0 so I don't think we'll be able to work on improving this functionality. See the changelog for details:
https://github.com/django/django-localflavor/blob/master/docs/changelog.rst#20---2017-12-30

Perhaps the recommended replacement `django-phonenumber-field` will have a solution for this.
https://github.com/stefanfoulis/django-phonenumber-field

Sorry we can't be more help here.

**Comment by darkpixel** [comment]
Thanks--I spaced on the new repo.
