### ISSUE TITLE
The ES translation of `North Carolina` has a preceding space

### ISSUE THREAD

**Issue by mkoistinen** [django/django-localflavor#395]
See here: https://github.com/django/django-localflavor/blob/master/localflavor/locale/es/LC_MESSAGES/django.po#L7601-L7602

Do I submit the fix directly here in the PO file or should someone do this in the translation service?

**Comment by claudep** [comment]
Yes, please fix it in Transifex directly.

**Comment by mkoistinen** [comment]
I requested to join the django-localflavor project at Transifex

**Comment by mkoistinen** [comment]
I cannot fix this in Transifex unless someone grants me permission to join the project there. I requested to join already, but it hasn't been permitted, and yet the translation issue still persists. I'm fine for closing this Issue as it's not a code issue, but what mechanism remains to ensure this isn't forgotten?

**Comment by claudep** [comment]
I applied the fix, it should be imported for the next release.
