### ISSUE TITLE
Django 3.0 Support / 3.0 Release: 19 February 2020

### ISSUE THREAD

**Issue by Palisand** [django/django-localflavor#398]
When is v3.0 (which I assume will support Django 3.0) scheduled to be released? Is there anything I can do to prioritize the next release?

**Comment by benkonrath** [comment]
Thanks for the reminder. I'll make a plan this evening and everything in motion. Hopefully we'll have it out within a week or two.

**Comment by benkonrath** [comment]
I can do the release on Wednesday 19 February. This gives me sometime to fix up and merge a few PRs.

@claudep Are you able to pull in an update from Tranifex that day? I can send a quick note to remind you on that day.

**Comment by claudep** [comment]
That should be OK. Can you please update the base catalog now (like c0123840494)?

**Comment by benkonrath** [comment]
Thanks for the reminder. The base catalogue has been updated.

**Comment by benkonrath** [comment]
@claudep Can you pull in the update from Transifex sometime today? Thanks.

**Comment by benkonrath** [comment]
django-localflavor 3.0 has now been released. Thanks.

**Comment by claudep** [comment]
Ben, our hero of the day :fireworks:

**Comment by Palisand** [comment]
Thank you all.
