### ISSUE TITLE
3.0.1 release on 25 March 2020

### ISSUE THREAD

**Issue by benkonrath** [django/django-localflavor#413]
See #410

**Comment by benkonrath** [comment]
@claudep Do you have time to update the translations from Transifex today? Sorry that I'm a little late asking. Tomorrow would also be ok. Thanks.

**Comment by claudep** [comment]
Hi Ben, I just realize that you accidentally reintroduced source comments in all po files in 9ebe417374, where only the `en` `django.po` should have been updated. Are you OK if I revert that commit?

**Comment by benkonrath** [comment]
Yeah, sure. Please revert the commit as needed.

I did notice there were more changes the last commit but I was using the invoke command which I assumed was more correct than when I manually update the base catalogue. Is this going to be a problem for the updated translations?

**Comment by claudep** [comment]
No, it should not. I guess you used the `make_translations` command without argument?

**Comment by benkonrath** [comment]
> I guess you used the make_translations command without argument?

Yeah, looks like it. I'll be sure to use `en` as argument next next. I guess I assumed it would default to `en` and didn't look closely. I supposed I could have figured it out with the extra changes. Thanks for noticing and fixing it.

**Comment by claudep** [comment]
I'll update that invoke script, making translations for all languages should generally not happen in our current workflow. I'ts currently misleading.

**Comment by claudep** [comment]
Updated translations are in now.

**Comment by benkonrath** [comment]
3.0.1 has just been released to pypi. Thanks for the help @claudep!

**Comment by claudep** [comment]
:tada:
