### ISSUE TITLE
US US_STATES is sorted incorrectly

### ISSUE THREAD

**Issue by ses4j** [django/django-localflavor#424]
https://github.com/django/django-localflavor/blob/master/localflavor/us/us_states.py 

The US_STATES enum is sorted by state code, but STATE_CHOICES (and old Django versions such as https://github.com/django/django/commit/4b2b2eda24) are sorted by state name.  The net effect is that Nevada SHOULD sort before New Jersey, but in fact sorts after since NV is after NJ.

**Comment by benkonrath** [comment]
@ses4j Thanks for letting us know. Any chance you can make a PR to fix this?

**Comment by ses4j** [comment]
@benkonrath done.
