### ISSUE TITLE
Update Chile to have new region

### ISSUE THREAD

**Issue by HectorAsencio** [django/django-localflavor#432]
CL: In 2018 the Bio Bio region was divided into two: Bio Bio (unchanged) and XVI Región de Ñuble (new).

**Comment by benkonrath** [comment]
Thanks for letting us know about the update. Do you have time to make a pull request to add this new region? Thanks.

**Comment by HectorAsencio** [comment]
Pull Request: https://github.com/django/django-localflavor/pull/433

**Comment by benkonrath** [comment]
Fixed via https://github.com/django/django-localflavor/commit/ad62cfe384accbdbddfb974b53ed1be76f96276b
