### ISSUE TITLE
3.1 Release: 27 May 2021

### ISSUE THREAD

**Issue by benkonrath** [django/django-localflavor#439]
String freeze 20 May 2021, release 27 May 2021.

@claudep Does this schedule work for you to pull in the translations from Transifex (on the 27th)? I'm happy to adjust the date if need be.

**Comment by claudep** [comment]
Sure!

**Comment by benkonrath** [comment]
@claudep Could you update the translations from Transifex whenever you have a chance? I'll probably do the release tomorrow - so no rush this evening. Thanks.

**Comment by claudep** [comment]
Thanks for the reminder, I'm doing it now.

**Comment by claudep** [comment]
Pushed 853c20b5bb and 9754e179755. Have a look!

**Comment by benkonrath** [comment]
Thanks!

**Comment by benkonrath** [comment]
https://pypi.org/project/django-localflavor/3.1/

Thanks for your help Claude!

**Comment by claudep** [comment]
:champagne:
