### ISSUE TITLE
Check import ordering with isort

### ISSUE THREAD

**Issue by claudep** [django/django-localflavor#447]

**Comment by benkonrath** [comment]
Do you mean you think we should put this back in?
https://github.com/django/django-localflavor/commit/00fe4ec9a81e142cd9237079698c1d4ee2884e7b

**Comment by claudep** [comment]
Oh I didn't remember this. Do you remember why you removed isort?

**Comment by benkonrath** [comment]
Too many contributors were having problems with it. I personally still like it but I thought making things a bit easier is more important than having sorted imports. The plan was to just run isort manually once in a while.

In my own projects use isort and black with pre-commit to run these tools. However, I get fewer contributors to these projects so it's less of an issue. In any case, I'm fine with turning the isort check on again if you think it's worthwhile.

**Comment by claudep** [comment]
I have a love-hate relationship with auto-formatting tools, so feel free to close the ticket if you feel like it.

**Comment by benkonrath** [comment]
I really like auto-formatting - especially when pre-commit is used. In this case, I think having a CI check for sorted imports will get in the way for less experienced contributors. I can just run isort manually once in a while. I'll make sure that I do this as a separate commit.
