### ISSUE TITLE
localflavor fields not showing up 

### ISSUE THREAD

**Issue by tambaTech** [django/django-localflavor#475]
Hello 

Can i please get som help, i'm kinda a newbie in Django.

Here is my Model: the fields are not showing up in the Django Administration.
What i'm i doing wrong? please help 

from localflavor.dk.forms import DKMunicipalitySelect, DKPostalCodeField

class Location(models.Model):
    address_1 = models.CharField(max_length=128, blank=True)
    address_2 = models.CharField(max_length=128, blank=True) 
    city = models.CharField(max_length=64)
    state = DKMunicipalitySelect()
    postal_code = DKPostalCodeField()

**Comment by claudep** [comment]
Sorry but this is not a help channel, it's a location to report bugs against the program. I suggest you go to Django forums to get help.
