### ISSUE TITLE
4.0 release 

### ISSUE THREAD

**Issue by benkonrath** [django/django-localflavor#481]
I'd like to make a 4.0 release in the coming weeks. Here's my proposed schedule:

* ~~1 April~~ 7 April: String / merge freeze
  * Update translation messages
  * Post a message to the translations forum asking for translations
* ~~14 April~~ 21 April: Make 4.0 release
  * Pull in translation on the morning of the 21th
 
@claudep Any feedback?

Edit: Updated the dates because of delays getting things ready on my side.

**Comment by benkonrath** [comment]
I plan to do some maintenance and look through the PRs. I'll make sure that I take care of points you mention. Thanks.

**Comment by benkonrath** [comment]
I'll be a little delayed on the string freeze 1 April. I'm hoping on or before Monday - I want to get #443 in.

**Comment by benkonrath** [comment]
I just updated the translations. I'd like to target 21 April for the release because I was delayed updating things.

**Comment by claudep** [comment]
No problem, thanks for the job!

**Comment by benkonrath** [comment]
@claudep Could you pull in the latest translations when you have a chance? Thanks!

**Comment by claudep** [comment]
Done in #487 (and I suggest to also merge #488).

**Comment by benkonrath** [comment]
4.0 has been released:
https://pypi.org/project/django-localflavor/4.0/

Thanks for the help @claudep!

**Comment by claudep** [comment]
Youhouuuuu! Many thanks Ben for your long-term commitment (which is so hard to get nowadays)! 🙏🏾
