### ISSUE TITLE
Add local-flavor support for Sri Lanka

### ISSUE THREAD

**Issue by dishansa** [django/django-localflavor#491]
Add support for Sri Lanka to the "django-localflavor" package. I would love to contribute to this feature. May I work on this, please?

**Comment by claudep** [comment]
You don't need permission, just suggest a patch with the required quality. Good coding!

**Comment by dishansa** [comment]
@claudep I am close to completing the development. And have two questions:

1, Changelog: How should I update the changelog file?
2, Testing: How can I test the project? (I wrote tests)

I am looking forward to hearing from you.
Thank You.
